
**Create a 5x5 array filled with random integers from 0 to 10.**
1. Create a 1D array of shape (5,) that will be added to each row of the 5x5 array using broadcasting.
2. Multiply each column of the 5x5 array by a 1D array of shape (5,) using broadcasting.
3. Display the final result.

In [ ]:
import numpy as np

arr = np.random.randint(0, 11, size=(5, 5))
add = np.random.randint(0, 11, size=(5,))
add_res = arr + add
col_mult = np.random.randint(0, 11, size=(5,))
final_result = add_res * col_mult[:, np.newaxis]

print("\nFinal Result:")
print(final_result)



Final Result:
[[ 90 117 108  90 117]
 [ 10  25  45  40  45]
 [ 27 108  81  63 126]
 [ 72  48  72  24  72]
 [  6  12  30  28  28]]


**Array Manipulation**
1. Create a 1D array with values from 1 to 20.
2. Reshape the array into a 4x5 matrix.
3. Flatten the reshaped matrix back into a 1D array.
4. ind the mean, standard deviation, and sum of the reshaped matrix.

In [ ]:
import numpy as np

arr = np.random.randint(1, 21, size=(20,))
newarr = arr.reshape(4, 5)
print(newarr)
flat_arr = newarr.flatten()
print(flat_arr)
print(np.mean(newarr))
print(np.std(newarr))
print(np.sum(newarr))

[[ 3 18 16 13  4]
 [ 9 15  8 20 17]
 [13 13 13 10 15]
 [ 1  7 12  5  5]]
[ 3 18 16 13  4  9 15  8 20 17 13 13 13 10 15  1  7 12  5  5]
10.85
5.265690837867335
217
