## Define the grid

### Subtask:
Create a 4x4 grid representing the environment, including obstacles.


**Reasoning**:
Create a 4x4 grid with obstacles, a start point, and an end point as instructed.



In [ ]:
import numpy as np

# Create a 4x4 grid
grid = np.zeros((4, 4))

# Add obstacles (represented by 1)
grid[1, 1] = 1
grid[2, 1] = 1
grid[2, 2] = 1

# Define start and end points
start = (0, 0)
end = (3, 3)

print("Grid with obstacles:")
print(grid)
print(f"Start point: {start}")
print(f"End point: {end}")

Grid with obstacles:
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Start point: (0, 0)
End point: (3, 3)


## Implement the a* algorithm

### Subtask:
Write a function to implement the A* algorithm, taking the grid, start point, and end point as input. This function should use the Manhattan distance as a heuristic and consider only horizontal and vertical moves.


**Reasoning**:
Implement the A* algorithm function as described in the instructions, including the heuristic and the main search logic.



In [ ]:
import heapq

def manhattan_distance(point1, point2):
    """Calculates the Manhattan distance between two points."""
    return abs(point1[0] - point2[0]) + abs(point1[1] - point2[1])

def astar(grid, start, end):
    """
    Implements the A* algorithm to find the shortest path in a grid.

    Args:
        grid (np.ndarray): The grid with obstacles (1) and free cells (0).
        start (tuple): The starting point (row, col).
        end (tuple): The ending point (row, col).

    Returns:
        list or None: The shortest path as a list of coordinates, or None if no path is found.
    """
    rows, cols = grid.shape
    open_set = []
    heapq.heappush(open_set, (0, start))  # (f_cost, node)

    came_from = {}
    g_cost = {start: 0}
    f_cost = {start: manhattan_distance(start, end)}

    while open_set:
        current_f, current_node = heapq.heappop(open_set)

        if current_node == end:
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start)
            path.reverse()
            return path

        # Explore neighbors (horizontal and vertical moves)
        for dr, dc in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            neighbor_row, neighbor_col = current_node[0] + dr, current_node[1] + dc
            neighbor_node = (neighbor_row, neighbor_col)

            # Check if the neighbor is within grid bounds and not an obstacle
            if (0 <= neighbor_row < rows and 0 <= neighbor_col < cols and
                    grid[neighbor_row, neighbor_col] == 0):

                tentative_g_cost = g_cost[current_node] + 1  # Cost of moving to a neighbor is 1

                  if neighbor_node not in g_cost or tentative_g_cost < g_cost[neighbor_node]:
                    g_cost[neighbor_node] = tentative_g_cost
                    f_cost[neighbor_node] = tentative_g_cost + manhattan_distance(neighbor_node, end)
                    heapq.heappush(open_set, (f_cost[neighbor_node], neighbor_node))
                    came_from[neighbor_node] = current_node

    return None  # No path found

# Test the astar function
path = astar(grid, start, end)

if path:
    print("Shortest path found:")
    print(path)
else:
    print("No path found.")

Shortest path found:
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 3), (2, 3), (3, 3)]


## Apply the algorithm

### Subtask:
Call the A* algorithm function with the defined grid, start point, and end point.


**Reasoning**:
Call the `astar` function with the defined grid, start point, and end point, store the result, and print it.



In [ ]:
path = astar(grid, start, end)

if path:
    print("Shortest path found:")
    print(path)
else:
    print("No path found.")

Shortest path found:
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 3), (2, 3), (3, 3)]
